# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMock():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_checkoutProduk(self):
    # Test name: Checkout Produk
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.saucedemo.com/")
    # 2 | setWindowSize | 1126x712 | 
    self.driver.set_window_size(1126, 712)
    # 3 | type | css=*[data-test="username"] | standard_user
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    # 4 | type | css=*[data-test="password"] | secret_sauce
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    # 5 | click | css=*[data-test="login-button"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    # 6 | click | css=*[data-test="shopping-cart-link"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()
    # 7 | click | css=*[data-test="checkout"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()
    # 8 | click | css=*[data-test="firstName"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").click()
    # 9 | type | css=*[data-test="firstName"] | Muhamad
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys("Muhamad")
    # 10 | type | css=*[data-test="lastName"] | Faroby
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys("Faroby")
    # 11 | type | css=*[data-test="postalCode"] | 61153
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys("61153")
    # 12 | click | css=*[data-test="continue"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()
    # 13 | click | css=*[data-test="finish"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()
    # 14 | click | css=*[data-test="back-to-products"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()
    # 15 | close |  | 
    self.driver.close()
  
  def test_login(self):
    # Test name: Login
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.saucedemo.com/")
    # 2 | setWindowSize | 1126x712 | 
    self.driver.set_window_size(1126, 712)
    # 3 | type | css=*[data-test="username"] | standard_user
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    # 4 | type | css=*[data-test="password"] | secret_sauce
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    # 5 | click | css=*[data-test="login-button"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    # 6 | close |  | 
    self.driver.close()
  
  def test_logout(self):
    # Test name: Logout
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.saucedemo.com/")
    # 2 | setWindowSize | 1126x712 | 
    self.driver.set_window_size(1126, 712)
    # 3 | type | css=*[data-test="username"] | standard_user
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    # 4 | type | css=*[data-test="password"] | secret_sauce
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    # 5 | click | css=*[data-test="login-button"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    # 6 | click | id=react-burger-menu-btn | 
    self.driver.find_element(By.ID, "react-burger-menu-btn").click()
    # 7 | click | css=*[data-test="logout-sidebar-link"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"logout-sidebar-link\"]").click()
    # 8 | close |  | 
    self.driver.close()
  
  def test_tambahProduk(self):
    # Test name: Tambah Produk
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.saucedemo.com/")
    # 2 | setWindowSize | 1126x712 | 
    self.driver.set_window_size(1126, 712)
    # 3 | type | css=*[data-test="username"] | standard_user
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    # 4 | type | css=*[data-test="password"] | secret_sauce
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    # 5 | click | css=*[data-test="login-button"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    # 6 | click | css=*[data-test="add-to-cart-sauce-labs-bike-light"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    # 7 | click | css=*[data-test="remove-sauce-labs-bike-light"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bike-light\"]").click()
    # 8 | click | css=#item_0_title_link > .inventory_item_name | 
    self.driver.find_element(By.CSS_SELECTOR, "#item_0_title_link > .inventory_item_name").click()
    # 9 | click | css=*[data-test="add-to-cart"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart\"]").click()
    # 10 | click | css=*[data-test="remove"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove\"]").click()
    # 11 | click | css=*[data-test="add-to-cart"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart\"]").click()
    # 12 | click | css=*[data-test="shopping-cart-link"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()
    # 13 | click | css=*[data-test="remove-sauce-labs-bike-light"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bike-light\"]").click()
    # 14 | close |  | 
    self.driver.close()
  
